name: "multilingual-welcome-action"
description: "A GitHub Action that provides customizable greetings in multiple languages"
author: "Itamar Zand"

branding:
  icon: "message-circle"
  color: "blue"

inputs:
  name:
    description: "The name of the person to greet"
    required: false
    default: "World"
  greeting_type:
    description: "Type of greeting (e.g., Hello, Hi, Good morning)"
    required: false
    default: "Hello"
  language:
    description: "Language for the greeting (en, es)"
    required: false
    default: "en"

runs:
  using: "composite"
  steps:
    - name: Set greeting
      shell: bash
      run: |
        if [[ "${{ inputs.language }}" == "en" ]]; then
          echo "GREETING=${{ inputs.greeting_type }}, ${{ inputs.name }}!" >> $GITHUB_ENV
        elif [[ "${{ inputs.language }}" == "es" ]]; then
          echo "GREETING=¡Hola, ${{ inputs.name }}!" >> $GITHUB_ENV
        fi

    - name: Print greeting
      shell: bash
      run: echo "${{ env.GREETING }}"
