name: "Hello Action"
description: "A simple GitHub Action that prints Hello World"
author: "Your Name"

inputs:
  name:
    description: "Your name"
    required: false
    default: "World"

runs:
  using: "composite"
  steps:
    - run: echo "Hello, ${{ inputs.name }}!"
      shell: bash
